software_new:
    path:     /new
    defaults: { _controller: "uniSistemasBundle:software:new" }

software_create:
    path:     /create
    defaults: { _controller: "uniSistemasBundle:software:create" }
    requirements: { _method: post }
    

